[package]
name = "max-capacity"
authors = ["Daniel Kolsoi <thadan64@gmail.com>"]
description = "A drop in tool for determining accuracy of max capacity usage"
version = "0.1.0"
edition = "2021"
readme = "README.md"

[dependencies]
log = { version = "0.4" }
uuid = { version = "1.1", features = ["v4"] }

[features]
default = []
